media:
  input: docs/assets
  output: /assets
content:
  - name: posts
    label: Posts
    type: collection
    path: docs/blog/posts
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: docs/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" } # This field may be ignored by MkDocs but is kept for PagesCMS
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: docs/assets, output: /assets } } # Ensure media paths here also align
