site_name: "The Chronicle of Franklin Baldo"
site_url: "https://franklinbaldo.github.io/mind-fragments"
site_author: "Franklin Baldo"
site_description: "A digital chronicle of Franklin Baldo's thoughts, projects, and intellectual journey. An experiment in autobiographical AI."

theme:
  name: material
  language: "en"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/feather # Placeholder, can be replaced with a custom logo
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/franklinbaldo"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/franklinbaldo" # Placeholder, Franklin to update if different
    - icon: fontawesome/solid/envelope
      link: "mailto:franklin@franklinbaldo.com" # Placeholder, Franklin to update

nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md
    - "Inaugural Post": blog/posts/2025-02-02-inaugural-post-a-glimpse-inside-my-mind.md
    - "Documento Conceitual": blog/posts/2024-07-12-documento-conceitual-a-cronica-de-franklin-baldo.md
    - "Patents For Social Vulnerabilities": blog/posts/2024-07-12-patents-for-social-vulnerabilities.md
    - "Pontifex Architecture Implementation Guide": blog/posts/2024-07-12-pontifex-architecture-implementation-guide.md
    - "Pontifex: A Novel Architecture for Semantic Probing": blog/posts/2024-07-12-pontifex-novel-architecture-semantic-probing.md
    - "Will AI Discover a New Conservation Law Before 2050?": blog/posts/2024-07-12-will-ai-discover-new-conservation-law-before-2050.md
    - "Adding new posts in Mind Fragments theme": blog/posts/adding-new-post.md
    - "Dynamic OG image generation in Mind Fragments blog posts": blog/posts/dynamic-og-images.md
    - "How to add a new Social Icon to Mind Fragments": blog/posts/how-to-add-a-new-social-icon.md
    - "How to update dependencies of Mind Fragments": blog/posts/how-to-update-dependencies.md
    - "How Do I Develop My Portfolio Website & Blog": blog/posts/portfolio-website-development.md
    - "Predefined color schemes": blog/posts/predefined-color-schemes.md
    - "Tailwind Typography Plugin": blog/posts/tailwind-typography.md
    - "How Do I Develop My Terminal Portfolio Website with React": blog/posts/terminal-development.md

plugins:
  - search
  
  
  - rss: # For RSS feed generation
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: "date"
        datetime_format: "%Y-%m-%d"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/franklinbaldo
      name: Franklin Baldo on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/franklinbaldo # Placeholder
      name: Franklin Baldo on Twitter
    - icon: fontawesome/solid/envelope
      link: mailto:franklin@franklinbaldo.com # Placeholder
      name: Send an email to Franklin Baldo
  analytics:
    provider: google # Or other analytics provider
    property: UA-XXXXXXXXX-X # Replace with actual Google Analytics ID

copyright: "Copyright &copy; 2024 Franklin Baldo"


